DTCalculator/urls.py
from django import views
from django.urls import path

from . import views

app_name = 'DTCalculator'
urlpatterns = [
    path('', views.applicationHomeView, name='home'),
    path('about/', views.aboutView, name='about'),
    path('report/', views.reportingViews, name='report'),
]

DinoSahrTipCalculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DTCalculator.urls')),
    path('about/', include('DTCalculator.urls')),
    path('report/', include('DTCalculator.urls')),
]

DTCalculator/models.py
from operator import index
from django.db import models
from django.utils import timezone

# Create your models here.
class Receipts(models.Model):
    receipt_date = models.DateTimeField(default=timezone.now)
    receipt_total = models.DecimalField(max_digits=7, decimal_places=2)
    TIP_SELECTOR = (
        ('default', 'Select Tip'),
        ('15', '15%'),
        ('18', '18%'),
        ('20', '20%'),
        ('22', '22%'),
        ('25', '25%')
    )
    tip_selector = models.CharField(
        max_length=20,
        choices=TIP_SELECTOR,
        default="Select Tip"
    )

    

    class Meta:
        ordering = ['receipt_date']

DTCalculator/views.py
from datetime import datetime
from django.shortcuts import render
from .models import Receipts
import pymongo

# Create your views here.

DB_USER='dinosahrdesign'
DB_PASS='Pmvsdz8bHuPYBk4w'
AUTH_DB='dinosahrdb'


total = ""
total_before_tip = ""
assigned_percent = "" 
tip_amount = ""
documents = ""
document_count = ""
total_with_tip = ""
grandTotalSpendings = ""
grandtotalBeforeTips = ""
grandtotalBeforeTips = ""
grandtotalTipsPaid = ""
results = ""


CONNECTION_URL =  'mongodb+srv://{}:{}@cluster0.iqkvm.mongodb.net/{}?retryWrites=true&w=majority'.format(DB_USER, DB_PASS, AUTH_DB)

client = pymongo.MongoClient(CONNECTION_URL, ssl=True, tlsAllowInvalidCertificates= True)
get_db_name = client.get_database('dtcalculator-receipts')
get_collection = get_db_name.get_collection(name='Receipts')


def applicationHomeView(request):

    if request.method == "POST":
        
        if request.POST.get('receipt-total-container') and request.POST.get('tip-percent-container'):

            receiptDate = datetime.strftime(datetime.today(), "%m/%d/%Y, %H:%M:%S")
            receiptTotal = request.POST.get('receipt-total-container')
            assignedTip = request.POST.get('tip-percent-container')

            tipPercent = float(assignedTip) /100

            finalAssignedTip = round(float(receiptTotal) * tipPercent, 2)

            grandTotal = round(float(receiptTotal) + finalAssignedTip, 2)

            global systemError, successfulSubmission, total, total_before_tip, assigned_percent, tip_amount, documents, document_count, total_with_tip


            total_before_tip = receiptTotal
            assigned_percent = int(tipPercent * 100)
            tip_amount = finalAssignedTip
            total_with_tip = grandTotal

            receipt = {
                '"Receipt_Date"': receiptDate,
                '"Total_Before_Tip"': float(receiptTotal),
                '"Tip_Percent_Assigned"': int(tipPercent * 100),
                '"Tip_Amount"': finalAssignedTip,
                '"Grand_Total"': grandTotal,
            }

            
            #Number of Receipts Added
            document_count = get_collection.count({}) + 1
            

            try:
                get_collection.insert_one(receipt)
                successfulSubmission = "Your connection request to the database was successful."
            except Exception as e:
                systemError = "The connection request to the database failed."
                

    return render(
        request, 
        'index.html', {
            'grandTotal': total, 
            'total_before_tip': total_before_tip, 
            'assigned_percent': assigned_percent, 
            'tip_amount':  tip_amount, 
            'document_count': document_count,
            'total_with_tip':  total_with_tip,
        }
    )


#ABOUT US PAGE VIEW
def aboutView(request):
    return render(request, 'about.html', {})




#REPORTING PAGE VIEW
def reportingViews(request):

    global grandTotalSpendings, grandtotalBeforeTips, grandtotalBeforeTips, grandtotalTipsPaid, results

    #Get total numner of receipts added to the database
    total_receipts = get_collection.count({})
    
    #REPORT GENERATOR FUNCTION
    def runAggregationReport(query):
        QueryData = get_collection.aggregate([
            {
                '$group': {
                    '_id': '',
                    'QueryParam': {
                        '$sum': query,
                    }
                }
            }
        ])

        for qD in QueryData:
            results = qD['QueryParam']
            if results != 'null' or 'none':
                return round(results, 2)
            else:
                return 0


    return render(request, 'report.html', {
            'total_receipts': total_receipts,
            'grandTotalSpendings': runAggregationReport('$"Grand_Total"'), 
            'grandtotalBeforeTips': runAggregationReport('$"Total_Before_Tip"'), 
            'grandtotalTipsPaid': runAggregationReport('$"Tip_Amount"'), 
        }
    )

DTCalculator/templates/about.html
{% extends 'base.html' %}

{% block aboutUsContent %}
    <h3>Our Story</h3>

    <div class="graphic" style="width: 100%; border: 1px solid #dee2e6; border-right: 0; border-left-width: 0.2rem; border-bottom-width: 0.2rem; border-top-width: 0.2rem;">
        <div class="shifter" style="padding: 1rem 0.5rem;">

            <h6>Purpose of this app</h6>
            <p>
                Though not enforced legally, but the allowed percentage limit on tipping in the Us is between 15-20%. Where Fifteen percent is considered the minimum of a decent tip, and 
                Twenty percent considered excellent. When your tip value is over this limit, some Financial Institutions would send you a confirmation email to confrim you did surely intended on giving the amount you'd
                given to your server or bartender as part of a tip for their service. And if you're me who usually get those confirmation email from your Financial Instution, then this app was built with you in 
                mind. This app ensures that you're never over the maximum allowed tipping limits. Andy by now you'd probably be asking how?. Well all you need to do is enter total on your
                receipt you get from your server or bartender. Then select the tip percentage you'd like to give between Fifteen Percent and Tweenty Percent, and hit the submit button, the app would provide
                you with a tip amount base on the percentage you'd selected and the final total after the tip amount is applied. The app also provide you with a real time report of
                the amount you'd spent on tips and your all your all time grand total spending from going out to bars and restaurants.
            </p>
        </div>
    </div>
    <div class="joinin-graphic" style="width: 100%;  border: 1px solid #dee2e6; border-top: 0; border-left: 0; border-left-width: 0.2rem; border-bottom-width: 0.2rem; border-right-width: 0.2rem;">
        <div class="shifter" style="padding: 1rem 0.5rem;">
            <h6 class="text-center">Future Updates Ideas</h6>
            <hr>
            <p class="future-updates-statement">
                Coming soon, you would be able to views reporting of your spending habits on a daily, weekly, monthly and yearly bases. This would allow myself or anyone using the app to track their spending at bars and restaurants.
                Thus enabling myself or anyone using the app to make changes such as going out less or getting fewer drink while out, allowing myself or anyone using the app to reduce spending and boost thier savings.
                I will also be implementing location service to the app later when I research the best services that won't cost an astronomical amount. <strong>Signup Page</strong>, <strong>Login Page</strong>, <strong>Password Reset</strong>, and <strong>Multi-Factor Authentication</strong> would be available soon.
            </p>
        </div>
    </div>
{% endblock %}

DTCalculator/templates/base.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/8308b68146.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'images/dtc-favicon.png' %}" type="image/x-icon">

    <title>DTCALCULATOR</title>
  </head>
  <body id="bg">
      <header class="primaryNav">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'DTCalculator:home' %}"><img src="{% static 'images/DTC-Official-Logo.png' %}" alt="App-Logo"><span class="app-name">DTCalculator</span></a>
              <!--<div class="logo-design"></div>--> 
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true"><a href="{% url 'DTCalculator:home' %}"><i class="fas fa-home"></i> Home</a></button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false"><a href="/about"><i class="fas fa-users"></i> About</a></button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="reports-tab" data-bs-toggle="tab" data-bs-target="#reports" type="button" role="tab" aria-controls="reports" aria-selected="false"><a href="/report"><i class="fas fa-chart-line"></i> Reports</a></button>
                    </li>
                    </ul>
              </div>
            </div>
          </nav>
      </header>

      <div class="container application-main-layout">
          
         <!-- Home Content -->
         {% block SiteRootContent %}
        
         {% endblock %}

         <!-- Reports Content -->
         {% block ReportContent %}
    
         {% endblock %}

         <!-- About Us Content -->
         {% block aboutUsContent %}

         {% endblock %}

      </div>
      
      <footer class="fixed-bottom">
        <div class="container">
            ©2022 <span class="site-name"><a class="site-name" href="{% url 'DTCalculator:home' %}">DTCalculator</a></span> - All Rights Reserved
        </div>
    </footer>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </body>
</html>

DTCalculator/templates/index.html
{% extends 'base.html' %}

{% block SiteRootContent %}
<h3>DinoSahr Tip Calculator Web Application.</h3>

<div class="graphic" style="width: 100%; border: 1px solid #dee2e6; border-right: 0; border-left-width: 0.2rem; border-bottom-width: 0.2rem; border-top-width: 0.2rem;">
    <div class="shifter" style="padding: 1rem 0.5rem;">
        <div class="container text-center home">
            <h6 class="text-center">New Receipt Entry Information</h6>
            <hr>   
        </div>
        <div class="row display-container">
            
            <div class="col-lg-4 total-before-tip">
                <h5 class="text-center">Final Total Before Tip</h5>
                <hr>
                <h6 class="text-center">${{total_before_tip}}</h6>
            </div>
            <div class="col-lg-4 assigned-tip">
                <h5 class="text-center">Tip Amount & Percentage</h5>
                <hr>
                <h6 class="text-center tip-amount-percent">${{tip_amount}} <br> <span>({{assigned_percent}})</span></h6>
            </div>
            <div class="col-lg-4 total-after-tip">
                <h5 class="text-center">Final Total After Tip</h5>
                <hr>
                <h6 class="text-center">${{total_with_tip}}</h6>
            </div>
        </div>
        <!-- <div class="divider-graphics"></div> -->
        <!-- <div class="container all-documents">
            <h5 class="title text-center">Number of Receipts</h5>
            <hr>
            {% if document_count == 0%}
                <h6>{{document_count_error}}</h6>
            {% else %}
                <h6 class="text-center">{{document_count}}</h6>
            {% endif %}
        </div> -->
    </div>
</div>
<div class="joinin-graphic" style="width: 100%;  border: 1px solid #dee2e6; border-top: 0; border-left: 0; border-left-width: 0.2rem; border-bottom-width: 0.2rem; border-right-width: 0.2rem;">
    <div class="shifter" style="padding: 1rem 0.5rem;">
        <form action="" method="POST">
            {% csrf_token %}
            <table class="DTC-Layout">
                <tbody>
                    <tr>
                        <td class="col-label">Receipt Total </td>
                        <td class="col-figure">
                            <input type="text" name="receipt-total-container" autocomplete="off">
                        </td>
                    </tr>
                    <tr>
                        <td class="col-label">Tip Percent</td>
                        <td class="col-figure">
                            <select name="tip-percent-container">
                                <option class="tip-percent-options">SELECT TIP PERCENTAGE BELOW</option>
                                <option class="tip-percent-options">15</option>
                                <option class="tip-percent-options">16</option>
                                <option class="tip-percent-options">17</option>
                                <option class="tip-percent-options">18</option>
                                <option class="tip-percent-options">19</option>
                                <option class="tip-percent-options">20</option>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <br>
            <button class="btn btn-outline-secondary" type="submit">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

DTCalculator/templates/report.html
{% extends 'base.html' %}

{% block ReportContent %}
    <h3>Reports</h3>
    
    <div class="graphic" style="width: 100%; border: 1px solid #dee2e6; border-right: 0; border-left-width: 0.2rem; border-bottom-width: 0.2rem; border-top-width: 0.2rem;">
        <div class="shifter" style="padding: 1rem 0.5rem;">
            <h6 class="text-center">Spending Report Summary</h6>
            <hr>
            <div class="container text-center home">
                <h5>All Time Grand Total Spending</h5>
                <hr>
                <h6 class="receipt-grand-total text-center aggreation">${{grandTotalSpendings}}</h6>
            </div>
            <div class="row">
                <div class="col-lg-6 total-before-tip">
                    <h5 class="text-center">Grand Total Before Tips</h5>
                    <hr>
                    <h6 class="text-center aggreation">${{grandtotalBeforeTips}}</h6>
                </div>
                <div class="col-lg-6 assigned-tip">
                    <h5 class="text-center">Grand Total Paid On Tips</h5>
                    <hr>
                    <h6 class="text-center aggreation">${{grandtotalTipsPaid}}</h6>
                </div>
            </div>
            <!-- <div class="divider-graphics"></div> -->
            <div class="all-documents">
                <h5 class="title text-center">Total Number of Receipts</h5>
                <hr>
                <h6 class="text-center">{{total_receipts}}</h6>
            </div>
        </div>
    </div>
    <div class="joining-graphic" style="width: 100%;  border: 1px solid #dee2e6; border-top: 0; border-left: 0; border-left-width: 0.2rem; border-bottom-width: 0.2rem; border-right-width: 0.2rem;">
        <div class="shifter" style="padding: 1rem 0.5rem;">
            <h6 class="text-center">Future Updates Ideas</h6>
            <hr>
            <p class="future-updates-statement">
                Coming soon, you would be able to views reporting of your spending habits on a daily, weekly, monthly and yearly bases. This would allow myself or anyone using the app to track their spending at bars and restaurants.
                Thus enabling myself or anyone using the app to make changes such as going out less or getting fewer drink while out, allowing myself or anyone using the app to reduce spending and boost thier savings.
            </p>
           
        </div>
    </div>
    
{% endblock %}